import { Datagrid } from '@mello-labs/datagrid';

export const columns: Datagrid.Column[] = [
  {
    prop: 'name',
    label: 'Loan Number',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'username',
    label: 'Borrower',
    columnType: 'string',
    width: 70,
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'username',
    label: 'Request Type',
    columnType: 'string',
    width: 70,
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'username',
    label: 'Documents',
    columnType: 'string',
    width: 70,
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
  {
    prop: 'website',
    label: 'Actions',
    columnType: 'string',
    canSort: true,
    canGroup: true,
    canFilter: true,
    canReorder: true,
    canResize: true,
    canDelete: true,
    canPinLeft: true,
    canEdit: true,
    canSearch: true,
  },
];
